version: "1"

services:
  frontend:
    build: ./infra/frontend/
    ports:
      - 8080:80
  db:
    build: ./infra/db/
    ports:
      - 5432:5432
    volumes:
      - ./infra/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devops
  backend:
    build: ./infra/backend/
    ports:
      - 3000:3000
    depends_on:
      - db
