version: "1"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    command: npm run build

  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"

  postgres:
    image: postgres:alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - "5432:5432"
