name: Publish Docker image

on:
  pull_request:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image - backend
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./infra/backend/Dockerfile
          push: true
          tags: mrdek/devops-exa-backend

      - name: Build and push Docker image - frontend
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./infra/frontend/Dockerfile
          push: true
          tags: mrdek/devops-exa-frontend

      - name: Build and push Docker image - db
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./infra/db/Dockerfile
          push: true
          tags: mrdek/devops-exa-db
