stages:
  - build_and_push

variables:
  DOCKER_IMAGE_PREFIX: "mrdek"

build_and_push:
  stage: build_and_push
  script:
    - docker login -u $USER -p $PASSWORD $REGISTRY

    # Build and push Backend image
    - docker build -t $DOCKER_IMAGE_PREFIX/devops-exa-backend:latest -f ../infra/backend/dockerfile .
    - docker push $DOCKER_IMAGE_PREFIX/devops-exa-backend:latest

    # Build and push Database image
    - docker build -t $DOCKER_IMAGE_PREFIX/devops-exa-db:latest -f ../infra/db/dockerfile .
    - docker push $DOCKER_IMAGE_PREFIX/devops-exa-db:latest

    # Build and push Frontend image
    - docker build -t $DOCKER_IMAGE_PREFIX/devops-exa-frontend:latest -f ../infra/frontend/dockerfile .
    - docker push $DOCKER_IMAGE_PREFIX/devops-exa-frontend:latest
  only:
    - master
