name: CI/CD

on:
  push:
    branches:
      - infra
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker backend
      run: |
        docker build -t devops-exa-backend:latest .
        docker push mrdek/devops-exa-backend

    - name: Set up Docker frontend
      run: |
        docker build -t devops-exa-frontend:latest .
        docker push mrdek/devops-exa-frontend

    - name: Set up Docker db
      run: |
        docker build -t devops-exa-db:latest .
        docker push mrdek/devops-exa-db

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
